language: php
php:
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'
  - '7.2'

sudo: false

cache:
  directories:
    - $HOME/.composer

env:
  - SYMFONY_VERSION=4.0.*
  - SYMFONY_VERSION=3.4.*
  - SYMFONY_VERSION=3.3.*
  - SYMFONY_VERSION=2.8.*

matrix:
  fast_finish: true

before_install:
  - composer selfupdate
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require --dev --no-update symfony/symfony:$SYMFONY_VERSION; fi

install:
    - composer install

script: php vendor/bin/phpunit
